name: ci

on:
  pull_request:
    branches:
      - "*"

jobs:
  test:
    uses: signoz/primus/.github/workflows/go-test.yaml@main
    secrets: inherit
    with:
      PRIMUS_REF: main
      GO_TEST_CONTEXT: ./...
      GO_TEST_TAGS: testing
  fmt:
    uses: signoz/primus/.github/workflows/go-fmt.yaml@main
    secrets: inherit
    with:
      PRIMUS_REF: main
  lint:
    uses: signoz/primus/.github/workflows/go-lint.yaml@main
    secrets: inherit
    with:
      PRIMUS_REF: main